"""Common genes shown as suggestions in the app's gene search box.

Users can still type any gene symbol; this list only powers the dropdown.
Symbols are the official human gene symbols (HGNC).
"""

COMMON_GENES = {
    # Oxygen transport and blood
    "HBA1": "hemoglobin subunit alpha 1",
    "HBB": "hemoglobin subunit beta",
    "HBD": "hemoglobin subunit delta",
    "HBG1": "hemoglobin subunit gamma 1",
    "MB": "myoglobin",
    "CYGB": "cytoglobin",
    "NGB": "neuroglobin",
    "EPO": "erythropoietin",
    "TF": "transferrin",
    "FTH1": "ferritin heavy chain 1",
    "ALB": "albumin",
    "FGB": "fibrinogen beta chain",
    "F8": "coagulation factor VIII",
    "F9": "coagulation factor IX",
    "VWF": "von Willebrand factor",
    # Cancer genes
    "TP53": "tumor protein p53",
    "BRCA1": "BRCA1 DNA repair associated",
    "BRCA2": "BRCA2 DNA repair associated",
    "KRAS": "KRAS proto-oncogene, GTPase",
    "NRAS": "NRAS proto-oncogene, GTPase",
    "HRAS": "HRas proto-oncogene, GTPase",
    "BRAF": "B-Raf proto-oncogene",
    "EGFR": "epidermal growth factor receptor",
    "ERBB2": "erb-b2 receptor tyrosine kinase 2 (HER2)",
    "MYC": "MYC proto-oncogene",
    "PTEN": "phosphatase and tensin homolog",
    "RB1": "RB transcriptional corepressor 1",
    "APC": "APC regulator of WNT signaling",
    "CDKN2A": "cyclin dependent kinase inhibitor 2A",
    "PIK3CA": "PI3-kinase catalytic subunit alpha",
    "AKT1": "AKT serine/threonine kinase 1",
    "MTOR": "mechanistic target of rapamycin kinase",
    "VHL": "von Hippel-Lindau tumor suppressor",
    "ATM": "ATM serine/threonine kinase",
    "CHEK2": "checkpoint kinase 2",
    "MLH1": "mutL homolog 1",
    "MSH2": "mutS homolog 2",
    "BCL2": "BCL2 apoptosis regulator",
    "MDM2": "MDM2 proto-oncogene",
    "IDH1": "isocitrate dehydrogenase 1",
    "ALK": "ALK receptor tyrosine kinase",
    "KIT": "KIT proto-oncogene",
    "ABL1": "ABL proto-oncogene 1",
    "JAK2": "Janus kinase 2",
    "NOTCH1": "notch receptor 1",
    "WT1": "WT1 transcription factor",
    "NF1": "neurofibromin 1",
    "SMAD4": "SMAD family member 4",
    "CTNNB1": "catenin beta 1",
    "ESR1": "estrogen receptor 1",
    "AR": "androgen receptor",
    # Hormones and signaling
    "INS": "insulin",
    "GCG": "glucagon",
    "LEP": "leptin",
    "GH1": "growth hormone 1",
    "PRL": "prolactin",
    "POMC": "proopiomelanocortin",
    "OXT": "oxytocin",
    "AVP": "arginine vasopressin",
    "IGF1": "insulin like growth factor 1",
    "GHRL": "ghrelin",
    "VEGFA": "vascular endothelial growth factor A",
    "TGFB1": "transforming growth factor beta 1",
    "TNF": "tumor necrosis factor",
    "IL6": "interleukin 6",
    "IL2": "interleukin 2",
    "IFNG": "interferon gamma",
    # Structure and muscle
    "ACTB": "actin beta",
    "ACTA1": "actin alpha 1, skeletal muscle",
    "TUBB": "tubulin beta class I",
    "TUBA1A": "tubulin alpha 1a",
    "MYH7": "myosin heavy chain 7",
    "TTN": "titin",
    "DMD": "dystrophin",
    "COL1A1": "collagen type I alpha 1 chain",
    "COL1A2": "collagen type I alpha 2 chain",
    "KRT14": "keratin 14",
    "ELN": "elastin",
    "LMNA": "lamin A/C",
    "VIM": "vimentin",
    "DES": "desmin",
    # Metabolism and enzymes
    "GAPDH": "glyceraldehyde-3-phosphate dehydrogenase",
    "ALDOA": "aldolase, fructose-bisphosphate A",
    "PGK1": "phosphoglycerate kinase 1",
    "ENO1": "enolase 1",
    "LDHA": "lactate dehydrogenase A",
    "CS": "citrate synthase",
    "CYCS": "cytochrome c, somatic",
    "SOD1": "superoxide dismutase 1",
    "CAT": "catalase",
    "GPX1": "glutathione peroxidase 1",
    "LYZ": "lysozyme",
    "AMY1A": "amylase alpha 1A",
    "LCT": "lactase",
    "ADH1B": "alcohol dehydrogenase 1B",
    "ALDH2": "aldehyde dehydrogenase 2",
    "CYP3A4": "cytochrome P450 3A4",
    "CYP2D6": "cytochrome P450 2D6",
    "G6PD": "glucose-6-phosphate dehydrogenase",
    "HPRT1": "hypoxanthine phosphoribosyltransferase 1",
    "HMGCR": "HMG-CoA reductase",
    "PAH": "phenylalanine hydroxylase",
    # Immune system
    "CD4": "CD4 molecule",
    "CD8A": "CD8 subunit alpha",
    "B2M": "beta-2-microglobulin",
    "TLR4": "toll like receptor 4",
    "IL1B": "interleukin 1 beta",
    "CXCL8": "C-X-C motif chemokine ligand 8",
    "FOXP3": "forkhead box P3",
    "MPO": "myeloperoxidase",
    # Brain and senses
    "APP": "amyloid beta precursor protein",
    "MAPT": "microtubule associated protein tau",
    "SNCA": "synuclein alpha",
    "HTT": "huntingtin",
    "BDNF": "brain derived neurotrophic factor",
    "PRNP": "prion protein",
    "FOXP2": "forkhead box P2",
    "SLC6A4": "serotonin transporter",
    "DRD2": "dopamine receptor D2",
    "RHO": "rhodopsin",
    "OPN1LW": "opsin 1, long wave (red)",
    # Development, stem cells and housekeeping
    "SOX2": "SRY-box transcription factor 2",
    "POU5F1": "POU class 5 homeobox 1 (OCT4)",
    "NANOG": "Nanog homeobox",
    "PAX6": "paired box 6",
    "SHH": "sonic hedgehog signaling molecule",
    "HOXA1": "homeobox A1",
    "FOXO3": "forkhead box O3",
    "SIRT1": "sirtuin 1",
    "TERT": "telomerase reverse transcriptase",
    "CFTR": "CF transmembrane conductance regulator",
    "MC1R": "melanocortin 1 receptor",
    "UBC": "ubiquitin C",
    "HSPA1A": "heat shock protein family A member 1A",
    "HSP90AA1": "heat shock protein 90 alpha A1",
    "EEF1A1": "eukaryotic translation elongation factor 1 alpha 1",
}
